# Generated by Django 6.0.6 on 2026-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview Scheduled', 'Interview Scheduled'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=30)),
                ('applied_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
