# Generated by Django 6.0.6 on 2026-06-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_notes',
            field=models.TextField(blank=True, help_text='Notes from interview rounds'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.CharField(blank=True, help_text='Version of resume used', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes'),
        ),
    ]
